sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "7"

cache:
  directories:
    - node_modules
    - bower_components
    - "$HOME/.npm"
    - "$HOME/.cache"

before_script:
    - npm install
before_deploy:
    - npm run build
env:
    NODE_ENV=testing
script:
  - npm run test
notifications:
  webhooks: https://fathomless-shore-84040.herokuapp.com/api/builds